### ISSUE TITLE
Improve the template for event posts

### ISSUE THREAD

**Issue by dadrasarmin** [usegalaxy-eu/galaxy-social#300]
There was a meeting and it was suggested to come up with an improved templates for posts based on the information from Galaxy Hub (this issue is only about the **events**). 

I prepared something here. Let's review it together and when it is finalized, @arash77 could implement it.

So, this is our Galaxy Hub metadata for events (Filled as a test event post):
```
title: "Galaxy Admin Training 2025"
date: "2025-01-20"
days: 4
tease: "Join us to learn how to set up and manage your own Galaxy server."
continent: EU
location: 
  name: "Freiburg, Germany"
  url: ""
external_url: "https://training.galaxyproject.org/training-material/events/2025-05-12-galaxy-academy-2025.html"
gtn: false
image:
contact: "contact@galaxy.cn"
tags: [admin, tiaas, training]
subsites: 
```

#### Mastodon template
```
📣 [title]

[tease]

📅 [date] [time]
📍 [location_or_online]

🔗 More info & registration:
[external_url or announcement_link]
[hashtags_based_on_tags and some usual one such as #useGalaxy #GalaxyProject]
```

And should become like: 

> 📣 Galaxy Admin Training 2025
> 
> Join us to learn how to set up and manage your own Galaxy server.
> 
> 📅 Jan 20–24
> 📍 Freiburg, Germany (and online)
> 
> 🔗 More info & registration:
> https://training.galaxyproject.org/training-material/events/2025-05-12-galaxy-academy-2025.html
> #useGalaxy #GalaxyProject #Admin #training #tiaas

#### Questions
1. Can we also include time? There is no metadata tag at the moment for time, correct? ([Is this the latest documentation?](https://github.com/galaxyproject/galaxy-hub/blob/master/CONTRIBUTING.md#page-metadata))
2. We need to filter out some tags. How can we do that? For example, `esg-wp3` should not be used but `esg` would be nice to have as a hashtag.  :)
3. If the post has an image as metadata, it could be used for the post. Correct?

What do you think? @arash77 @bgruening
